
server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb+srv://auth:auth@auth.uxlqz.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name : Customer-Service
  main:
   allow:
    circular:
      references: true
